name: Release
on:
    push:
        branches:
            - main
            - beta

jobs:
    version:
        timeout-minutes: 15
        runs-on: ubuntu-20.04
        strategy:
            matrix:
                node-version: [18.12.1]
        steps:
            - name: Wait for commit-check to succeed
              uses: lewagon/wait-on-check-action@v1.2.0
              with:
                ref: ${{ github.ref }}
                running-workflow-name: 'Commit Check'
                repo-token: ${{ secrets.GITHUB_TOKEN }}
                wait-interval: 120
                allowed-conclusions: success
            - name: Wait for test to succeed
              uses: lewagon/wait-on-check-action@v1.2.0
              with:
                ref: ${{ github.ref }}
                running-workflow-name: 'Test'
                repo-token: ${{ secrets.GITHUB_TOKEN }}
                wait-interval: 120
                allowed-conclusions: success
            - name: Wait for type-check to succeed
              uses: lewagon/wait-on-check-action@v1.2.0
              with:
                ref: ${{ github.ref }}
                running-workflow-name: 'Type Check'
                repo-token: ${{ secrets.GITHUB_TOKEN }}
                wait-interval: 120
                allowed-conclusions: success
            - name: Wait for lint to succeed
              uses: lewagon/wait-on-check-action@v1.2.0
              with:
                ref: ${{ github.ref }}
                running-workflow-name: 'Lint'
                repo-token: ${{ secrets.GITHUB_TOKEN }}
                wait-interval: 120
                allowed-conclusions: success
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  registry-url: 'https://registry.npmjs.org'
                  cache: 'npm'
            - run: npm ci
            # The build is for this repo
            - run: npm run build
            - run: npx --no -- semantic-release --debug
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
